src/clj_time/coerce.clj
test/clj_time/coerce_test.clj

Right now, to-epoch returns a ratio when the current time has a non-zero milliseconds part. This code ensures that it will always return an integer number of seconds, and adds a test for that case.
Authors:
Tanya Romankova
Eli Naeher

to-epoch should always return an integer number of seconds

---

README.md

I was puzzled why the namespace alias was not there for this example. Then I realized it was just missing in the README. This PR fixes that.

Adding the missing namespace alias to the example

---

src/clj_time/core.clj
test/clj_time/core_test.clj

The great Joda library has a property called WeekOfWeekyear,
the week-number-of-year function exposes that.
Uses the suggested name discussed in [PR 166](https://github.com/clj-time/clj-time/pull/166#issuecomment-72400776).

Adding 'week-number-of-year -> maps to Joda WeekOfWeekyear

---

README.md
src/clj_time/core.clj
test/clj_time/core_test.clj

This gives us symmetry with `before?` and `after?`.
Further discussion in #90.

Add `equal?` predicate

---

project.clj
src/clj_time/jdbc.clj
test/clj_time/jdbc_test.clj

This change adds an optional development dependency on clojure.java.jdbc which
is required for tests. Presumably, users of the protocol extensions will already
have clojure.java.jdbc included in their projects, and we don't want to force
the dependency on anyone who uses clj-time.
I'm also unsure what the best method is for testing these other than to verify that the protocols are extended as we expect (as I've done) without bringing in a bigger mocking framework a la clojure.java.jdbc. This may be OK as-is.
Reference: #149

Add clojure.java.jdbc protocol extensions for easier coercion

---

README.md
src/clj_time/core.clj
test/clj_time/core_test.clj

`overlap` returns an Interval whenever the arguments satisfy `overlaps?`,
otherwise it returns nil.
Two cases to higlight:
* When null is passed to joda-time's overlap method it means 'a zero
duration interval at now'. Therefore when nil is passed as the second
argument of `overlap` we should return the overlap of the first argument
and a zero duration interval with both start and end times equal to the
current time.
* Two zero duration intervals at the same DateTime do not satisfy
`overlaps?` (they satisfy `abuts?`) so `overlap` should return nil in this
case.

Add `overlap` that returns the overlap of two intervals.

---

src/clj_time/instant.clj

This is a port of the relevant bits of Monger's `monger.joda-time`. @seancorfield let me know if this is something you'd be happy with.
Fixes #179.

Introduce clj-time.instant

---

src/clj_time/coerce.clj
test/clj_time/coerce_test.clj

My use case centers around having instants (in UTC) but wanting to be able to render the correct date on the server for non-browser clients in other time zones than the server time zone (also UTC). If there's a better way to do this please let me know. Thanks.

Accept optional tz argument for to-local-date.

---

src/clj_time/coerce.clj
src/clj_time/core.clj
src/clj_time/format.clj
src/clj_time/local.clj
test/clj_time/coerce_test.clj
test/clj_time/core_test.clj
test/clj_time/format_test.clj
test/clj_time/local_test.clj
test/clj_time/periodic_test.clj
test/clj_time/predicates_test.clj

This is only cleanup related to style and issues found by [Eastwood](https://github.com/jonase/eastwood), there should be no functional changes.
- Remove unlimited :use references
- Be more consistent with use of square brackets in :import references

Clean up ns declarations

---

test/clj_time/core_test.clj

An issue found by https://github.com/jonase/eastwood
`(= Exception)` is trivially true, so it seems the intent was to compare this against the return values of `earliest` and `latest`. However, I've only updated the tests to pass with the current behavior, I'm not sure if the current behavior is actually desired. It seems `nil` simply compares before all other dates/times.

Fix tests with mistaken 1-arg `=` calls

---

src/clj_time/jdbc.clj
test/clj_time/jdbc_test.clj

Don't know how many databases out there actually represent dates and times as separate types (different from timestamps) but I don't think it'll hurt to cover them.

Adds sql.Date and sql.Time auto-coerce to clj-time.jdbc

---

src/clj_time/format.clj
test/clj_time/format_test.clj

- Avoids reflection, but adds a map lookup.
- We look if fmts is in the formatters map first.  If not, we assume it
is a string, and can be retrieved with the normal
`DateTimeFormat/forPattern` approach.
- I'm not sure why there was a `(declare formatter)` block given that
formatter is the very next function in the ns, but I changed it
to `(declare formatters)`, and now that is meaningful as well.

Allow formatter to accept keyword args.

---

project.clj

Hey :smile: 
Just a small change for better inclusion of `org.clojure/clojure` :smile:

Change org.clojure/clojure to "provided"

---

project.clj
src/clj_time/core.clj
test/clj_time/local_test.clj

Adds type hints where indicated by compiler, and enable refection warnings in
leiningen builds to help avoid future regressions.

Fix reflection warnings

---

.travis.yml

Add .m2 directory in cache on travis.
This will result in builds running faster.

On travis Add .m2 dir in cache

---

project.clj
src/clj_time/spec.clj
src/clj_time/types.clj
test/clj_time/types_test.clj
test_clj_1.9/clj_time/spec_test.clj

This addresses issue #220.
I thought it would be useful to define generators to go with the predicates. Since everyone's requirements are probably different for generated dates, I put the actual generator for the range in milliseconds in a dynamic function called `*period*`, which I tried to set up with somewhat sensible defaults.
I was unable to cause the date-time generator to use time zones in the way I expected them to work, but I'm not certain if that's important. If it is I hope someone will be able to fix it. I don't see it as a serious issue if it is not fixed, or if the entire time zone related stuff is scrapped.
The dynamic generators are in functions because when they are evaluated the test.check dependency is triggered. Just like with clojure.spec, the namespace can still be …

Define some type predicates and related clojure.spec definitions.

---

src/clj_time/coerce.clj
src/clj_time/format.clj

Since clj-time doesn't wrap all of joda-time api, I thought it would be convenient to type-hint return values that are instances from joda-time, for cases where users call the native library because they have no clj-time wrapper.

return type hints

---

src/clj_time/core.clj
test/clj_time/core_test.clj

Closes #239
Open to suggestions to what to call this thing. Think [ISO 8601](iso-weekyear) calls it a "week year", and the corresponding week "week number".
[iso-weekyear]: https://en.wikipedia.org/wiki/ISO_week_date

Exposing week-year field

---

src/clj_time/coerce.clj

Change `if-let` to `when-let` because only "then" is used,
so i think it's more idiomatic to use `when-let`

Change `if-let` to `when-let` 

---

src/clj_time/core.clj
test_clj_1.9/clj_time/inst_test.clj

The change proposed here extends the `Inst` protocol to `org.joda.time.ReadableInstant` when `clj-time.core` is loaded. Since `Inst` was only added in Clojure 1.9, the extension is conditional on availability of `Inst`.
This should resolve #248.
Notes about the changes:
* Of all the Joda-Time API classes the interface `org.joda.time.ReadableInstant` (which is implemented by `org.joda.time.DateTime`) seems best suited for extension to `Inst`.
* I renamed the Leiningen profile `:spec` to `:1.9` to better reflect what’s in the tests (not just spec).
This changeset seems reasonable to me but of course I am happy to incorporate any feedback you might have.

Extend Inst to org.joda.time.ReadableInstant on Clojure 1.9

---

test/clj_time/format_test.clj

Helps to have a instant reference of how to use by just looking at the tests.

Add tests for builtin time formatters with parser

---

src/clj_time/coerce.clj
src/clj_time/core.clj
src/clj_time/format.clj

* Add type hints in a few namespaces, if doing so was unmistakable
* Correct existing type hints position
* See https://clojure.org/reference/java_interop#typehints
* Also see https://gist.github.com/pjstadig/6fa4ebf465f6d438b4dcc2a5bfbb3db6s

Add or fix various type hints
